version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - notes-db
      - meilisearch
    networks:
      - laravel-network

  notes-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    networks:
      - laravel-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work
    volumes:
      - .:/var/www
    depends_on:
      - notes-db
      - meilisearch
    networks:
      - laravel-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    volumes:
      - .:/var/www
    depends_on:
      - notes-db
      - meilisearch
    networks:
      - laravel-network

  npm_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/var/www
    depends_on:
      - notes-db
      - meilisearch
    networks:
      - laravel-network

volumes:
  mysql-data:

networks:
  laravel-network: