<?php

namespace Tests\Unit;

use App\Models\Note;
use App\Models\User;
use App\Utilities\Trash;
use Tests\TestCase;

class TrashTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        auth()->logout();
    }

    public function test_remove_expired()
    {
        $user = User::factory()->create();
        auth()->login($user);

        Note::factory()->for($user, 'owner')->create()
                       ->delete();

        $this->travel(-8)->days();
        Note::factory()->for($user, 'owner')->create()
                        ->delete();

        $this->assertCount(2, Note::onlyTrashed()->get());

        $this->travelBack();
        Trash::removeExpired();
        $this->assertCount(1, Note::onlyTrashed()->get());
    }

    public function test_empty()
    {
        $user = User::factory()->create();
        auth()->login($user);

        Note::factory()->count(5)->for($user, 'owner')->create()->each->delete();
        $this->assertCount(5, Note::onlyTrashed()->get());

        Trash::empty();
        $this->assertEmpty( Note::onlyTrashed()->get() );
    }

    public function test_trash_is_emptied_for_specific_user()
    {
        $user_1 = User::factory()->create();
        $user_2 = User::factory()->create();

        Note::factory()->count(5)->for($user_1, 'owner')->create()->each->delete();
        Note::factory()->count(5)->for($user_2, 'owner')->create()->each->delete();

        auth()->login($user_1);
        Trash::empty();

        $this->assertCount(5, Note::onlyTrashed()->where('owner_id', $user_2->id)->get());

        auth()->logout();
        auth()->login($user_2);
        Trash::empty();

        $this->assertEmpty(Note::onlyTrashed()->get());
    }
}
